DROP TABLE IF EXISTS location_code;

CREATE TABLE location_code(
	country	VARCHAR(30) NOT NULL PRIMARY KEY,
	latitude DOUBLE PRECISION NOT NULL,	
	longitude DOUBLE PRECISION NOT NULL,
	inflation_2022 DOUBLE PRECISION NOT NULL,
	code VARCHAR(3) NOT NULL
);

SELECT * FROM location_code;