DROP TABLE IF EXISTS location_db;

CREATE TABLE location_db(
	country	VARCHAR(30) NOT NULL PRIMARY KEY,
	latitude DOUBLE PRECISION NOT NULL,	
	longitude DOUBLE PRECISION NOT NULL,
	inflation_2022 DOUBLE PRECISION NOT NULL	
);

SELECT * FROM location_db;